name: hawc_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - sasktran2
  - xarray
  - scipy
  - numpy
  - matplotlib
  - pandas
  - cartopy
  - notebook
  - numba        # required by hawcsimulator; conda-forge version avoids llvmlite issues
  - pip
  - pip:
    - hawcsimulator
    - cesm-hawc   # install this package in editable mode after cloning
